spring:
  application:
    name: kotlin-market-scanner
  r2dbc:
    url: ${DB_URL:r2dbc:h2:mem:///market_scanner;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.r2dbc: INFO
